"""
LEGALMET AI — PDF Report Generator
Generates an AI-Assisted Preliminary Inspection Report using ReportLab.

All reports carry a visible statutory disclaimer:
"AI-assisted preliminary assessment based on submitted image evidence.
This system does not replace statutory inspection, measurement or legal
determination by an authorized officer."
"""
import os
from datetime import datetime
from typing import Optional
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image as RLImage
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import KeepTogether
from sqlalchemy.orm import Session
from backend.database.models import (
    Inspection, Declaration, RuleResult, Evidence, ManualReview,
    DeclarationStatus, InspectionStatus
)

STATUTORY_DISCLAIMER = (
    "AI-ASSISTED PRELIMINARY ASSESSMENT: This report is generated by the LEGALMET AI "
    "system and is based on automated analysis of submitted image evidence. It constitutes "
    "a preliminary screening tool for enforcement officers. This report does NOT constitute "
    "a final statutory determination, legal conviction, or certified compliance clearance. "
    "Final determination of compliance or non-compliance remains exclusively with the "
    "authorized officer under the Legal Metrology Act, 2009 and related rules."
)

STATUS_COLORS = {
    InspectionStatus.PASS: colors.HexColor("#10b981"),
    InspectionStatus.POTENTIAL_NON_COMPLIANCE: colors.HexColor("#ef4444"),
    InspectionStatus.MANUAL_REVIEW: colors.HexColor("#f59e0b"),
}

DECL_STATUS_SYMBOL = {
    DeclarationStatus.FOUND: "✓ FOUND",
    DeclarationStatus.NOT_FOUND: "✗ NOT FOUND",
    DeclarationStatus.NOT_APPLICABLE: "— N/A",
    DeclarationStatus.UNCERTAIN: "⚠ UNCERTAIN",
    DeclarationStatus.MANUAL_REVIEW: "👁 MANUAL REVIEW",
}


def generate_pdf_report(inspection: Inspection, db: Session, reports_dir: str) -> str:
    """
    Generate a PDF AI-Assisted Preliminary Inspection Report.
    Returns the file path of the generated PDF.
    """
    os.makedirs(reports_dir, exist_ok=True)
    filename = f"LEGALMET_{inspection.inspection_id}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(reports_dir, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Header ────────────────────────────────────────────────────────────────
    title_style = ParagraphStyle("Title", parent=styles["Title"],
                                 fontSize=16, textColor=colors.HexColor("#0f172a"),
                                 spaceAfter=4, alignment=TA_CENTER)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"],
                                    fontSize=10, textColor=colors.HexColor("#64748b"),
                                    spaceAfter=2, alignment=TA_CENTER)
    story.append(Paragraph("LEGALMET AI", title_style))
    story.append(Paragraph("AI-Assisted Preliminary Inspection Report", subtitle_style))
    story.append(Paragraph(
        "Ministry of Consumer Affairs, Food &amp; Public Distribution | Department of Consumer Affairs",
        subtitle_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#2563eb")))
    story.append(Spacer(1, 6))

    # ── Inspection Metadata ───────────────────────────────────────────────────
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=11,
                        textColor=colors.HexColor("#1e293b"), spaceBefore=8, spaceAfter=4)
    normal = ParagraphStyle("Normal", parent=styles["Normal"], fontSize=9, spaceAfter=2)

    meta_data = [
        ["Inspection ID", inspection.inspection_id],
        ["Product Name", inspection.product_name or "—"],
        ["Brand", inspection.brand_name or "—"],
        ["Category", inspection.product_category.value.replace("_", " ").title()],
        ["Inspector", inspection.inspector.full_name if inspection.inspector else "—"],
        ["Date", inspection.created_at.strftime("%d %B %Y, %H:%M UTC") if inspection.created_at else "—"],
        ["Completed", inspection.completed_at.strftime("%d %B %Y, %H:%M UTC") if inspection.completed_at else "—"],
    ]
    if inspection.is_demo:
        meta_data.insert(0, ["⚠ DEMO FLAG", inspection.demo_label or "CONTROLLED DEMO TEST CASE"])

    meta_table = Table([[Paragraph(f"<b>{k}</b>", normal), Paragraph(v, normal)] for k, v in meta_data],
                       colWidths=[55 * mm, 110 * mm])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")),
        ("PADDING", (0, 0), (-1, -1), 4),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 8))

    # ── Overall Assessment Banner ─────────────────────────────────────────────
    status_color = STATUS_COLORS.get(inspection.status, colors.grey)
    status_label = inspection.status.value.replace("_", " ")
    conf = f"{inspection.overall_confidence:.0%}" if inspection.overall_confidence else "—"

    banner_style = ParagraphStyle("Banner", parent=styles["Normal"],
                                  fontSize=14, textColor=colors.white,
                                  alignment=TA_CENTER, spaceBefore=6, spaceAfter=6)
    banner_table = Table(
        [[Paragraph(f"<b>PRELIMINARY ASSESSMENT: {status_label}</b>", banner_style),
          Paragraph(f"<b>Prototype Confidence: {conf}</b>", banner_style)]],
        colWidths=[110 * mm, 55 * mm]
    )
    banner_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), status_color),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(banner_table)
    story.append(Spacer(1, 8))

    # ── Declaration Checks ────────────────────────────────────────────────────
    story.append(Paragraph("Declaration Analysis", h2))
    declarations = db.query(Declaration).filter(Declaration.inspection_id == inspection.id).all()
    rule_results = db.query(RuleResult).filter(RuleResult.inspection_id == inspection.id).all()
    rule_map = {r.declaration_field: r for r in rule_results}

    decl_rows = [
        [
            Paragraph("<b>Declaration Field</b>", normal),
            Paragraph("<b>Status</b>", normal),
            Paragraph("<b>Extracted Value</b>", normal),
            Paragraph("<b>Confidence</b>", normal),
            Paragraph("<b>Legal Reference</b>", normal),
        ]
    ]

    rendered_fields = set()
    for decl in declarations:
        rr = rule_map.get(decl.field)
        status_text = DECL_STATUS_SYMBOL.get(decl.status, decl.status.value)
        conf_text = f"{decl.extraction_confidence:.0%}" if decl.extraction_confidence else "—"
        legal_ref = rr.legal_reference if rr else "—"
        decl_rows.append([
            Paragraph(decl.field.replace("_", " ").title(), normal),
            Paragraph(status_text, normal),
            Paragraph(decl.extracted_value or "—", normal),
            Paragraph(conf_text, normal),
            Paragraph(legal_ref[:60] + "..." if len(legal_ref) > 60 else legal_ref, normal),
        ])
        rendered_fields.add(decl.field)

    # Show rule results for fields with no declaration (NOT_FOUND, NOT_APPLICABLE)
    for rr in rule_results:
        if rr.declaration_field not in rendered_fields:
            status_text = DECL_STATUS_SYMBOL.get(rr.status, rr.status.value)
            decl_rows.append([
                Paragraph(rr.declaration_field.replace("_", " ").title(), normal),
                Paragraph(status_text, normal),
                Paragraph("—", normal),
                Paragraph("—", normal),
                Paragraph(rr.legal_reference[:60] + "..." if len(rr.legal_reference) > 60 else rr.legal_reference, normal),
            ])

    col_widths = [48 * mm, 28 * mm, 38 * mm, 20 * mm, 35 * mm]
    decl_table = Table(decl_rows, colWidths=col_widths)
    decl_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#cbd5e1")),
        ("PADDING", (0, 0), (-1, -1), 4),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(decl_table)
    story.append(Spacer(1, 8))

    # ── Potential Issues Section ──────────────────────────────────────────────
    issues = [rr for rr in rule_results if rr.status in (
        DeclarationStatus.NOT_FOUND, DeclarationStatus.UNCERTAIN
    ) and rr.severity in ("HIGH", "MEDIUM")]

    if issues:
        story.append(Paragraph("Potential Issues Identified", h2))
        warn_style = ParagraphStyle("Warn", parent=styles["Normal"], fontSize=9,
                                    textColor=colors.HexColor("#7c2d12"), spaceAfter=4)
        for i, rr in enumerate(issues, 1):
            story.append(Paragraph(
                f"<b>{i}. {rr.declaration_field.replace('_', ' ').title()}</b> — "
                f"Status: {rr.status.value} | Severity: {rr.severity}<br/>"
                f"Rule: {rr.legal_reference}<br/>"
                f"Details: {rr.details}",
                warn_style
            ))
        story.append(Spacer(1, 4))

    # ── Inspector Manual Review ───────────────────────────────────────────────
    manual_review = db.query(ManualReview).filter(ManualReview.inspection_id == inspection.id).first()
    if manual_review and manual_review.decision:
        story.append(Paragraph("Inspector Review Decision", h2))
        review_data = [
            ["Decision", manual_review.decision.value.replace("_", " ").title()],
            ["Reviewed At", manual_review.reviewed_at.strftime("%d %B %Y, %H:%M") if manual_review.reviewed_at else "—"],
            ["Statutory Notes", manual_review.statutory_notes or "—"],
            ["Flagged Declarations", ", ".join(manual_review.flagged_declarations or []) or "—"],
        ]
        review_table = Table([[Paragraph(f"<b>{k}</b>", normal), Paragraph(v, normal)] for k, v in review_data],
                             colWidths=[55 * mm, 110 * mm])
        review_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#fef3c7")),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#fcd34d")),
            ("PADDING", (0, 0), (-1, -1), 4),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(review_table)
        story.append(Spacer(1, 8))

    # ── Statutory Disclaimer ──────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#94a3b8")))
    story.append(Spacer(1, 4))
    disclaimer_style = ParagraphStyle("Disclaimer", parent=styles["Normal"],
                                      fontSize=7.5, textColor=colors.HexColor("#64748b"),
                                      spaceAfter=4, leading=11)
    story.append(Paragraph(STATUTORY_DISCLAIMER, disclaimer_style))
    story.append(Paragraph(
        f"Generated by LEGALMET AI — SIH Problem Statement SIH26034 | {datetime.utcnow().strftime('%d %B %Y %H:%M UTC')}",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7,
                       textColor=colors.HexColor("#94a3b8"), alignment=TA_CENTER)
    ))

    doc.build(story)
    return filepath
